# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTemplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'SwiftyJSON'
#  pod 'RealmSwift'

  # Pods for iOSTemplate

  target 'iOSTemplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
